### ISSUE TITLE
install.sh doesn't work on some linux arm

### ISSUE THREAD

**Issue by adasauce** [hyprspace/hyprspace.github.io#2]
Systems like raspi and other SBCs report aarch64 for `uname -m`. as far as I'm aware, they are the same architecture as `arm64` under different names.

This patch allowed me to install on my SBC and is working.

Also, `tr` trims `aarch64` to `arch64`. uname -m doesn't return any uppercase characters so it should be safe to just parse it as it's returned.

```patch
diff --git a/install.sh b/install.sh
index bdbf025..aa5752f 100644
--- a/install.sh
+++ b/install.sh
@@ -92,7 +92,7 @@ execute_sudo() {

 # Use uname to determine the computer's ARCH and OS.
 os=$( echo "$(uname -s)" | tr -s  '[:upper:]'  '[:lower:]' )
-arch=$( echo "$(uname -m)" | tr -s  '[:upper:]'  '[:lower:]' )
+arch=$( echo "$(uname -m)" )

 # Get the latest tagged release from GitHub.
 latest=$(get_latest_release)
@@ -103,6 +103,10 @@ if [ "$arch" == "x86_64" ]; then
         arch="amd64"
 fi

+if [[ "$arch" == "aarch64" ]]; then
+        arch="arm64"
+fi
+
 if [[ "$os" == "darwin" ]]; then
     if [[ "$arch" == "arm64" ]]; then
        install_dir=/opt/hyprspace
```

**Comment by alecbcs** [comment]
Oh curious! I haven't gotten the chance to try out the install script yet on a Raspberry Pi but this all looks good to me. Would you be interested in packaging this up into a PR? I'd really like to give you credit for updating the install script rather than just applying your patch under my own name.
